language: php
php:
  - '7.3'
before_script: composer install --prefer-source --no-interaction
script: phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
deploy:
  github_token: $GH_TOKEN
  api_key:
    secure: $GH_TOKEN
